### PR TITLE
build,ci: Python 3.12 support

### PR DESCRIPTION
**Pull request by maartenbreddels**

### CODE REVIEW

**Comment by iisakkirotko** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/widgetti/reacton/26?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26** <a href="https://app.graphite.dev/github/pr/widgetti/reacton/26?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/widgetti/reacton/26?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#39** <a href="https://app.graphite.dev/github/pr/widgetti/reacton/39?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#40](https://github.com/widgetti/reacton/pull/40) <a href="https://app.graphite.dev/github/pr/widgetti/reacton/40?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by maartenbreddels** [comment]
Some some reason I cannot approve, so doing it with: 👍

**Comment by iisakkirotko** [comment]
Right, can't approve your own PRs 😆

**Comment by iisakkirotko** [comment]
### Merge activity

* **Dec 16, 9:57 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/widgetti/reacton/26).

**Pull request merged**
